config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  post '/posts',  to: 'posts#index'
  get  '/posts',  to: 'posts#index'
  get  '/post' ,  to: 'posts#new'
  post '/post' ,  to: 'posts#create'
  get  '/login',  to: 'sessions#new'
  post '/login',  to: 'sessions#create'
  delete  '/logout', to: 'sessions#destroy'
  resources :users, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    validates :title, presence: true
    validates :body,  presence: true

    belongs_to :user, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
    attr_accessor :remember_token
    before_create :create_remember_digest

    validates :name, length: {minimum: 4, maximum: 20}, presence: true
    validates :email, length: {maximum: 255}, presence: true, uniqueness: {case_sensitive: false}
    validates :password, length: {minimum: 6, maximum: 255}, presence: true

    has_secure_password
    has_many :posts, foreign_key: "user_id"

    # Returns the hash digest of the given string.
    def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                    BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end

    # Returns a random token.
    def User.new_token
        SecureRandom.urlsafe_base64
    end

    # Remembers a user in the database for use in persistent sessions.
    def remember
        self.remember_token = User.new_token
        update_attribute(:remember_digest, User.digest(remember_token))
    end

    def authenticated?(remember_token)
        return false if remember_digest.nil?
        BCrypt::Password.new(remember_digest).is_password?(remember_token)
    end

    private

        def create_remember_digest
            self.remember_token = User.new_token
            self.remember_digest = User.digest(remember_token)
        end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    include SessionsHelper
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :logged_in?, only:[:new, :create]

    def new
        @post = Post.new
    end

    def create
        @post = Post.new(post_params)
        if @post.save
            redirect_to posts_path
        else
            render 'new'
        end
    end

    def index
        @posts = Post.all
    end

    private
        def post_params
            params.require(:post).permit(:title, :body, :user_id)
        end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      log_in user
      remember user
      redirect_to root_url
    else
      flash.now[:danger] = "This account does not exist"
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    def home
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
    end
    
    def show
        @user = User.find(params[:id])
    end

    def create
        @user = User.new(user_params)
        if @user.save
            log_in @user
            UserMailer.with(user: @user).welcome_email.deliver_now
            redirect_to root_url
        else
            render 'new'
        end
    end

    private

    def user_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user)
        session[:user_id] = user.id
    end

    def remember(user)
        user.remember
        cookies.permanent[:remember_token] = user.remember_token
        cookies.permanent.signed[:user_id] = user.id
    end

    def forget(user)
        cookies.delete(:remember_token)
        cookies.delete(:user_id)
    end

    def current_user
        if session[:user_id]
            @current_user ||= User.find_by(id: session[:user_id])
        elsif cookies.signed[:user_id]
            @current_user = User.find_by(id: cookies.signed[:user_id])
            if @current_user && @current_user.authenticated?(cookies[:remember_token])
                log_in @current_user
                @current_user
            end
        end
    end

    def log_out
        session.delete(:user_id)
        cookies.delete(:user_id)
        cookies.delete(:remember_token)
        @current_user = nil
    end

    def logged_in?
        !current_user.nil?
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
        <nav>
            <ul>
                <li><%= link_to "Home", root_path %></li>
                <li><%= link_to "Posts", posts_path %></li>
                <% if logged_in? %>
                    <li><%= link_to "Create post", post_path %></li>
                    <li><%= link_to "Log out", logout_path, method: :delete %></li>
                <% else %>
                    <li><%= link_to "Sign Up", new_user_url %></li>
                    <li><%= link_to "Login", login_path %></li>
                <% end %>
            </ul>
        </nav>
    </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Members Only</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true%>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/index.html.erb
<h1>Posts</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <% @posts.each do |post| %>
        <div style="border: solid 1px rgb(210,210,210)">
            <h3><%= post.title %></h3>
            <h6><%= "Author: #{User.find(post.user_id).name}" if logged_in? %></h6>
            <p><%= post.body %></p>
        </div>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<h1>Create post</h1>
<div>
  <div>
    <%= form_for @post do |f| %>
      <%= f.hidden_field :user_id, value: current_user.id %>
      <%= f.label :title %><br>
      <%= f.text_field :title %><br>

      <%= f.label :body %><br>
      <%= f.text_area :body %><br>

      <%= f.submit "Create post" %>
    <% end %>

  </div>
</div>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to the Members-only App</h1>

  <h2>
    This is the home page for my Members-Only App.
  </h2>

  <% unless logged_in? %>
    <%= link_to "Sign up now!", '#', class: "btn btn-lg btn-primary" %>
  <% end %>
</div>

app/views/users/new.html.erb
<h1>Sign up</h1>
<div>
  <div>
    <%= form_for(@user) do |f| %>
        <%= f.label :name %>
        <%= f.text_field :name %><br>

        <%= f.label :email %>
        <%= f.email_field :email %><br>

        <%= f.label :password %>
        <%= f.password_field :password %><br>

        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation %><br>

        <%= f.submit "Sign up" %>
    <% end %>
  </div>
</div>